# Generated by Django 5.2.5 on 2025-08-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='sdfsdfsdf'),
        ),
    ]
