# Generated by Django 5.2.5 on 2025-08-09 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FACTORY', 'factory'), ('CENTRAL_OFFICE', 'Central office'), ('SHOW_ROOM', 'Show room')], default='FACTORY', max_length=55)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('description', models.TextField(blank=True, verbose_name='communicate with us')),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='field name')),
                ('url', models.URLField(verbose_name='link url')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='icon')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='accounts.contactinfo')),
            ],
        ),
    ]
