# Generated by Django 5.2.5 on 2025-08-13 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 11 digits.', regex='^\\d{11}$')])),
                ('message', models.TextField(blank=True, verbose_name='communicate with us')),
            ],
        ),
    ]
