# Generated by Django 5.2.5 on 2025-08-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_communicationwithus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationwithus',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
